# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /newswebsite

# Installing dependencies
COPY ./package.json /newswebsite
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start
